/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CoordJDialog.java
 *
 * Created on Dec 11, 2010, 10:55:38 AM
 */

package pCSDT.Presentation;

/**
 *
 * @author tylau
 */
public class CoordJDialog extends javax.swing.JDialog {

    String coordStr = null;

    /** Creates new form CoordJDialog */
    public CoordJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public void SetTextFieldX(String str) {
        this.jTextFieldx.setText(str);
    }

    public void SetTextFieldY(String str) {
        this.jTextFieldy.setText(str);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelx = new javax.swing.JLabel();
        jTextFieldx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldy = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButtonOK = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Enter Coordinates");

        jLabelx.setText("(x, y) = (");

        jTextFieldx.setText("0");
        jTextFieldx.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextFieldx.setPreferredSize(new java.awt.Dimension(30, 20));
        jTextFieldx.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldxKeyReleased(evt);
            }
        });

        jLabel2.setText(",");

        jTextFieldy.setText("0");
        jTextFieldy.setMinimumSize(new java.awt.Dimension(30, 20));
        jTextFieldy.setPreferredSize(new java.awt.Dimension(30, 20));
        jTextFieldy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldyActionPerformed(evt);
            }
        });
        jTextFieldy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldyKeyReleased(evt);
            }
        });

        jLabel3.setText(")");

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelx)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOK)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelx)
                    .addComponent(jTextFieldx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOK)
                    .addComponent(jButtonCancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldyActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldyActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        coordStr = jTextFieldx.getText().trim() + "," + jTextFieldy.getText().trim();
        this.setVisible(false);
}//GEN-LAST:event_jButtonOKActionPerformed

    public void EnablingOKButton() {
        if (isNum(jTextFieldx.getText().trim()) && isNum(jTextFieldy.getText().trim())) {
            this.jButtonOK.setEnabled(true);
        }
        else {
            jButtonOK.setEnabled(false);
        }
    }
    private void jTextFieldxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldxKeyReleased
        // TODO add your handling code here:
        EnablingOKButton();
    }//GEN-LAST:event_jTextFieldxKeyReleased

    private void jTextFieldyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldyKeyReleased
        // TODO add your handling code here:
        EnablingOKButton();
    }//GEN-LAST:event_jTextFieldyKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CoordJDialog dialog = new CoordJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelx;
    private javax.swing.JTextField jTextFieldx;
    private javax.swing.JTextField jTextFieldy;
    // End of variables declaration//GEN-END:variables

    private boolean isNum(String s) {
        try {
            Double.parseDouble(s);
        }
        catch (NumberFormatException nfe) {
            return false;
        }
        return true;
    }
}
